# Generated by Django 5.1.4 on 2024-12-21 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_alter_pharmacyuser_options_pharmacyuser_groups_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pharmacyuser",
            options={
                "permissions": [
                    ("view_sales", "Can view pharmacy sales"),
                    ("manage_sales", "Can manage pharmacy inventory"),
                    ("view_purchases", "Can view pharmacy purchases"),
                    ("manage_purchases", "Can manage pharmacy purchases"),
                    ("view_prescriptions", "Can view prescriptions"),
                    ("manage_prescriptions", "Can manage prescriptions"),
                    ("manage_users", "Can manage pharmacy staff"),
                    ("view_customers", "Can view pharmacy customers"),
                    ("manage_customers", "Can manage pharmacy customers"),
                    ("view_reports", "Can view pharmacy reports"),
                    ("view_suppliers", "Can view pharmacy suppliers"),
                    ("manage_supplers", "Can manage pharmacy suplliers"),
                ]
            },
        ),
    ]
