# Generated by Django 5.1.4 on 2024-12-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useradmin", "0003_alter_purchase_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="quantity",
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
