# Generated by Django 5.1.4 on 2024-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useradmin", "0005_rename_consumer_prescription_customer_sales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sale_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
