# Generated by Django 5.1.4 on 2024-12-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useradmin", "0006_alter_sales_sale_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sales",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="sales",
            name="quantity",
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useradmin.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sales",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="useradmin.cart",
            ),
        ),
        migrations.CreateModel(
            name="CartMedicines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="useradmin.cart"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="useradmin.medicine",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="useradmin.prescription",
                    ),
                ),
            ],
        ),
    ]
