# Generated by Django 5.1.4 on 2024-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("useradmin", "0007_remove_sales_medicine_remove_sales_prescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
